config/routes.rb
Rails.application.routes.draw do

  # Routes for sessions_controller

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy"

  # Routes for users_controller

  get '/signup', to: "users#new"
  post '/signup', to: "users#create"
  resources :users

  # Routes for static_pages_controller

  root "static_pages#home"
  get '/help', to: "static_pages#help"
  get '/about', to: "static_pages#about"
  get '/contact', to: "static_pages#contact"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  validates :content, length: {maximum: 140}
end

app/models/user.rb
class User < ApplicationRecord

  before_save { self.email = email.downcase }

  validates :name, presence: true, length: {maximum: 50}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }
  validates :email, uniqueness: { case_sensitive: false }

  has_secure_password

  validates :password, presence: true, length: {minimum: 6}

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : Crypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = "Login Failed: Invalid Email/Password"
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Your Account has been created successfully!"
      redirect_to @user
    else
      render 'new'
      flash[:danger] = "Account Registration could not be completed!"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    base_title = "Sample App"
    if page_title.empty?
      return title
    else
      title = page_title + " | " + base_title
    end
    title
  end


end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    if current_user.nil?
      return false
    else
      return true
    end
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/layouts/_footer.html.erb
<footer class= "footer" >
  <hr>
  <small>Built using Ruby on Rails</small>
  <nav>
    <ul class="footer-nav">
      <li><%= link_to "About" , about_path %></li>
      <li><%= link_to "Help" , help_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <% if logged_in? %>
            <li> <%= link_to "Users" , "#" %> </li>
            <li class= "dropdown" >
              <a href= "#" class= "dropdown-toggle" data-toggle= "dropdown" > Account <b class= "caret" ></b> </a>
              <ul class= "dropdown-menu" >
                <li> <%= link_to "Profile" , current_user %> </li>
                <li> <%= link_to "Settings" , "#" %> </li>
                <li class= "divider" ></li>
                <li> <%= link_to "Log out" , logout_path %> </li>
              </ul>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield :title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render 'layouts/header' %>

  <% if (yield :title) != "Home"  %>
    <h1 class="center"><%= yield :title %></h1>
    <br>
  <% end %>

  <% flash.each do |key, message| %>
    <div class="alert alert-<%= key %>"><%= message %></div>
  <% end %>

  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>

  </body>
</html>

app/views/microposts/_form.html.erb
<%= form_for(micropost) do |f| %>
  <% if micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Microposts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.content %></td>
        <td><%= micropost.user_id %></td>
        <td><%= link_to 'Show', micropost %></td>
        <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
        <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @micropost.user_id %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

app/views/shared/_signup_errors.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger">
    <h3>Your application form contains following <%= pluralize (@user.errors.count), "error" %></h3>
    <ul>
      <% @user.errors.full_messages.each do|msg| %>
          <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<p> <b>Project under: </b>The
  <a href= " http://www.railstutorial.org/ " ><em> Ruby on Rails Tutorial: </em></a>
  A
  <a href= " http://www.railstutorial.org/book " > book </a>
  and <a href= "http://screencasts.railstutorial.org/" > screencast tutorial.</a>
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact")  %>

<h2>Shreenath Tewari</h2>
<br>

<ul class="contact-list">
  <li>
    <h4>Mobile: </h4>
    <h5>9840375894/9474830172</h5>
  </li>
  <li>
    <h4>
      Blogs:
      <h5>
        <li><%= link_to "Personal", "https://tewarishreenath.wordpress.com/" %></li>
        <li><%= link_to "Passion", "https://humanwarblog.wordpress.com/" %></li>
      </h5>
    </h4>
  </li>
</ul>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<p>Help Page for Sample App</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<div class="center jumbotron" >
  <h1 class="page-title"> Welcome to the Sample App </h1>
  <h2 class="home-body"> This is the home page for the <a href="http://www.railstutorial.org/" > Ruby on Rails Tutorial </a> sample application. </h2>
  <%= link_to "Sign Up now!" , signup_path , class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("rails.png" , alt: "Rails logo"), 'http://rubyonrails.org/', class: "rails-img" %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>

<div class="row">

  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user) do |f| %>

      <%= render 'shared/signup_errors'  %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control" %><br>

      <%= f.submit "Create Account", class: "btn btn-primary" %>

    <% end %>

  </div>

</div>

app/views/users/show.html.erb
<% provide(:title, "#{@user.name}") %>

<div class="gravatar-name">
  <h1>
    <%= gravatar_for(@user) %>
    <%= @user.name %>
  </h1>
</div>